Mint trackers
traderjoe-xyz/launchpeg pull request #22
Opened 2022-05-19 14:08 UTC by Mathieu-Be

Adding mint counters to be displayed on the UI + `amountForMintlist` for FlatLaunchpeg

2022-05-19 14:19 UTC, Max-3-7 reviewed
Great stuff, thank you very much 🔥

2022-05-19 14:19 UTC, Max-3-7 commented on contracts/BaseLaunchpeg.sol
> +        }
Should we do that and remove the one above?

```suggestion
        if (_amountForMintlist + _amountForDevs > _collectionSize) {
            revert Launchpeg__LargerCollectionSizeNeeded();
        }
```

2022-05-19 14:19 UTC, Max-3-7 commented on contracts/FlatLaunchpeg.sol
> +        amountMintedDuringMintlist += _quantity;
Should we make sure in this function that it's not possible to mint more than `amountForMintlist` as we do in Launchpeg?

```solidity
if (amountMintedDuringMintlist + _quantity > amountForMintlist) {
    revert Launchpeg__MaxSupplyReached();
}
```

2022-05-19 15:54 UTC, cryptofish7 requested changes
Make sure you search through all instances of `allowList` and change to `allowlist`.

Likewise, do the same for `mintList` and `mintlist`.

Also, I noticed we use mintlist and allowlist synonymously, which is really confusing. Can we stick to one? (My preference would be allowlist)

2022-05-19 15:54 UTC, cryptofish7 commented on contracts/BaseLaunchpeg.sol
> +    /// @notice Amount of NFTs available for the allowList mint (e.g 1000)
`allowlist`

2022-05-19 15:54 UTC, cryptofish7 commented on contracts/BaseLaunchpeg.sol
> +    /// @param _amountForMintlist Amount of NFTs available for the allowList mint (e.g 1000)
`allowlist`

2022-05-20 09:15 UTC, Mathieu-Be commented
Changed every `mintlist` into `allowlist`. @Max-3-7 you might have some `mintlist` in the front-end as well.

2022-05-20 09:30 UTC, Max-3-7 commented
Yeah i'll update the FE so we are aligned as well @Mathieu-Be

2022-05-20 15:57 UTC, merged