Vrf reveal
traderjoe-xyz/launchpeg pull request #30
Opened 2022-06-09 08:51 UTC by Mathieu-Be

Implementing VRF for Launchpeg. A few notes : 
- I kept `forceReveal()` with pseudo-randomness for safety
- Multisig will need to add the launchpeg contract to its list of VRF consumers.

An example on Fuji can be found [here](https://testnet.snowtrace.io/address/0x5932677b3f981d718114dc9b713beec51e2c9c08)

Not related but I noticed that the tests were forking mainnet. I removed it, I think it was unnecessarily slowing down the tests.

2022-06-10 07:39 UTC, cryptofish7 requested changes

2022-06-10 14:27 UTC, Mathieu-Be commented on contracts/BatchReveal.sol
> +            vrfRequestedForBatch[batchNumber] = true;
The coordinator already emits an event on `requestRandomWords`, with all the VRF params and the address of the msg.sender

2022-06-10 16:30 UTC, Mathieu-Be commented on contracts/BatchReveal.sol
> +        nextBatchToReveal++;
Does the `++` on `nextBatchToReveal` happens before or after being initializing `_batchToReveal` ?

2022-06-10 18:01 UTC, Mathieu-Be commented on contracts/BaseLaunchpeg.sol
> +    ) external onlyOwner {
I went for the first option as I see no reasons to lock the parameters. Also added some validation

2022-06-10 18:05 UTC, LouisMeMyself commented on contracts/BatchReveal.sol
> +        nextBatchToReveal++;
After, that's why it's so elegant!

If you wanted to do it before, it would be `++nextBatchToReveal`.

2022-06-10 18:20 UTC, Mathieu-Be commented
Deployed a new contract on Fuji : https://testnet.snowtrace.io/address/0xa8e171869fc5a8da7183d535906d0fca76a51b41

2022-06-11 09:36 UTC, cryptofish7 requested changes
Small nit

2022-06-11 09:36 UTC, cryptofish7 commented on contracts/BatchReveal.sol
> +    /// @notice Number of block confirmations that will the coordinator wait before triggering the callback
`Number of block confirmations that the coordinator will wait before triggering the callback`

2022-06-11 16:21 UTC, LouisMeMyself requested changes
Good stuff!

2022-06-11 16:21 UTC, LouisMeMyself commented on contracts/BaseLaunchpeg.sol
> +                keyHashFound = true;
Add `break` when found

2022-06-11 16:21 UTC, LouisMeMyself commented on contracts/BaseLaunchpeg.sol
> +                isInConsumerList = true;
Add `break` when found

2022-06-14 18:31 UTC, cryptofish7 approved these changes

2022-06-14 18:31 UTC, merged